openai_api_key = "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"
gemini_api_key = "AQ.Ab8RN6LgoyJZwkWm4f1_ko1rLsbAd9Mg4PeTiFs2PHKEAE0wgg"
groq_api_key = "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"